import React, { useEffect } from 'react'
import { Helmet } from "react-helmet";
import Navbar from '../components/Navbar';
import Footer from '../components/Footer';

function TermsAndCondition() {

    function updateMetaTags() {

        const titleElement = document.querySelector("title");
        const metaTitleElement = document.querySelector('meta[name="title"]');
        const descriptionElement = document.querySelector('meta[name="description"]');

        let title = "Terms and Condition | FiYDAA";
        let description = "This Terms and Condition applies to all the users whose personal information has been processed by us in the course of our business, mobile applications, forums, blogs, and other online or offline offerings.";


        titleElement.textContent = title;
        metaTitleElement.setAttribute("content", title);
        descriptionElement.setAttribute("content", description);
    }

    useEffect(() => {
        updateMetaTags();
    })

    return (
        <>
            <Navbar />

            <div style={{ width: '70%', margin: 'auto', marginTop: '20px', marginBottom: '20px', textAlign: 'justify', fontFamily: 'Poppins' }}>

                <div style={{ margin: 'auto', marginBottom: '20px', textAlign: 'center' }}>
                    <h1 class="text-3xl font-poppins mb-4" align="center">FiYDAA Terms and Condition</h1>
                </div>
                <p class="text-2xl font-poppins mb-4">Terms and Condition :</p>


                This document is an electronic record in terms of Information Technology Act, 2000, amendments thereof from time to time and the rules thereunder as applicable and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures.
                Please read the terms of use carefully before registering, accessing or using the FiYDAA Services (defined below). The terms and conditions are a legal contract ("Agreement") between You and Clearwater Capital Private Limited ("FiYDAA/Company”) having its registered office at 1st FLOOR, 945/3, Pachranga Bazar, Panipat, Haryana, 132103, India. You agree and acknowledge that you have read the terms and conditions set forth below. If you do not agree to these terms and conditions or do not wish to be bound by these terms and conditions, you may not use the Services and/or immediately terminate the Services and/or uninstall the mobile application.
                <br /><br />

                We may amend the terms and conditions at any time by posting an updated version at the website and Mobile App (App/Platform). The updated version of the Terms of Service shall take effect immediately upon posting. Your continued use of the App following the posting of changes will mean that You accept and agree to the revisions, including additional Terms or removal of portions of these Terms, modifications etc.<br /><br />


                <p class="text-2xl font-poppins mb-4">Definition :</p>

                “We”, “Us”, “Our” - shall refer to Clearwater Capital Private Limited“You”, “Yours”, “Yourself”, “User”- refers to any non-registered individual or corporate body, registered user of the App,including but not limited to users of services provided by FiYDAA “FiYDAA App” - The mobile application(s), hosted by FiYDAA and for providing FiYDAA services to its users, including its business partners and service providers and also includes any and all Services where it acts as an Intermediary . “FiYDAA Services” - shall include all services extended but not limited to purchase/investment of Gold and other similar investment line. “Business Partners” – Shall refer to any individual, group of individuals defined under law with whom FiYDAA have a contractual relationship and not limited to Clients, Advertisers, Financial institutions. <br /><br />

                <p class="text-2xl font-poppins mb-4">Eligibility :</p>
                By accessing the Service and FiYDAA App You represent that:-<br />
                1) You are 18 years of age or older <br />
                2) You are capable of entering into a contract /legally binding agreement <br />
                3) You have the right, authority and capability to enter into this Agreement abiding by all the provisions of the “terms of use” <br />
                4) You are not impersonating any person or entity, or falsely stating your age or affiliation with any person or entity. FiYDAA shall reserve the right to terminate your contract to use in case of any incorrect representation of the above-mentioned conditions. <br />
                5) The mandatory information and Officially valid document(s) “OVD”/ document details mentioned by you are true & correct and belong to You. <br />
                6) We will at all times assume (and by using this App you warrant that) you have the legal ability to purchase and sell Gold and otherwise use this Platform, and are capable of being bound by these Terms and Conditions. <br />
                7) Further, by using the App, You confirm that you are not registered under any applicable Goods and Services Tax Act, 2017 and that if, in the course of your relationship with our App and/or one of our Business Partner, you become registered under the applicable Goods and Services Tax Act, 2017, you shall inform our business partner of your change in status immediately. <br />
                8) If necessary, you shall seek independent tax advice, and these Terms and Conditions do not constitute any tax advice to You. <br /><br />

                <p class="text-2xl font-poppins mb-4">Registration :</p>
                In order to use the Services You need to register on the FiYDAA App/Platform and provide us with accurate and complete information as required. You are also required to keep your accounts, KYC details and contact information complete and updated at all times. <br />
                Once you sign-up on App you are entitled to a FiYDAA Account. Once registered, certain services may ask you for additional information in order or avail such service and may involve creation of sub-accounts for availing such services. <br /><br />

                <p class="text-2xl font-poppins mb-4">FiYDAA Services :</p>
                FiYDAA Account An account that you create when you sign-up/register with FiYDAA to access the Services, including the following:<br /><br />
                1) This account allows you to access the App, browse through the Service, make payment using UPI, debit card, credit cards or net banking collectively known as (‘Payment Gateway Services’) as permissible for the investment purchase of Gold<br />
                2) The Company may also ask You to provide certain additional information about yourself on a case-to-case basis.<br />
                3) Access to FiYDAA Account enables you to browse through FiYDAA Services provided by FiYDAA and in order to avail, enroll or use any such Service you may need to additionally register for such services by providing some more information as required under the Terms of Use of such products/services.<br />
                4) Allows you to share and maintain the Know Your Customer “KYC” details and information for underwriting purposes for other financial and non-financial products available on the App<br />
                5) You further agree to the Privacy Policy as applicable for Clearwater Capital Entity. In order to avail the Services, you need a mobile, internet or any other supported device that meets the compatibility requirements of accessing the app and the website, which may change from time to time.<br />
                6) You are allowed to purchase Gold pursuant to the collaboration between the Company and Augmont Gold.<br />
                7) The Company hereby grants You, a limited, non-exclusive, non-transferable, royalty free license to use the App/Platform for the purposes of availing the Services.<br />
                8) The services offered on the Platform shall include, but is not limited to the following:<br /> (a) facilitating buying and selling of Gold; and (b) maintaining a record of Your personal information and financial transactions in a secure and confidential manner;. (“Platform Services”).<br />
                9) However, before placing the order and availing the Services, the User may be required to provide certain KYC documentation and other information as may be required by the Business Partner( Currently Augmont, the same shall be updated from time to time) in such form and manner as it may deem fit.<br />
                10) This information may be requested from You at the time of registration, or at a later stage, including the following events, to prevent fraudulent activities: You withdraw your purchase of Gold; and/or wish to get Your Customer Gold delivered to Your doorstep.<br />
                11) The KYC verification shall be undertaken based on the PAN Card issued to You.<br />
                You shall provide your KYC details in cases where PAN card details are required.<br />
                12)  If You do not have a PAN Card, you may submit Form 60 to Us. It is hereby clarified that any Services offered (purchase, sale or transfer of Gold on Augmont’s platform) are governed under specific terms and conditions of Augmont, operated and managed by Gold India Private Limited which can be accessed at {""} <a href="https://www.augmont.com/terms-conditions" style={{ color: '#0043e9' }}> https://www.augmont.com/terms-conditions</a><br />
                13) The Purchase only Digital Gold to start with on a pre-payment basis, with an applicability of 3% GST on all purchases. No KYC is required for purchase upto 29 gms of gold. The gold once purchased cannot be sold before 48 hours of purchase.<br />
                14) It is also clarified that the Company is merely providing a platform to its Users to facilitate the transaction of sale and investment of Gold and will not be liable in any manner with respect to the products and/or services offered to You by the respective Business Partners<br />
                15) You hereby agree and acknowledge that the data and information provided on the App does not constitute advice of any nature whatsoever and shall not be relied upon by You while making investment decisions and You shall be solely responsible for any investment decisions and for the purchase of any Gold on the App.<br />
                16) In no event shall the Company be liable to You for any loss or damage that may cause or arise from or in relation to these Terms of Use and/or due to use of this App/Platform or due to investments made using this App/Platform.<br />
                17) Use of the App/Platform and availing the Services: You acknowledge that the Services are for Your personal use and agree not to publish the Gold prices or descriptions of Gold and/or any other information displayed on the Platform (in lieu of Your access to the App/Platform) on any other medium.<br />
                18) You agree that You shall not copy, reproduce, sell, redistribute, publish, enter into a database, display, perform, modify, alter, transmit, license, create derivatives from, transfer or in any way exploit any part of any information, content, materials, services available from or through the App/Platform, except that You may download the App for Your own personal, internal and non-commercial use.<br />
                19) You agree that You will not use the App/Platform in any manner or engage in any activity that may damage, disable or impair or adversely affect the use of the Platform or interfere with any other users’ use, legal rights, or enjoyment of the Platform. Further, You agree not to remove any text, copyright or other proprietary notices contained in the content downloaded from the App/Platform.<br /><br />

                <p class="text-2xl font-poppins mb-4">Placing of order :</p>
                1) You can purchase Gold on the Platform on a pre-payment basis i.e., once you place the order and confirm the transaction for purchase of Gold, and agree to the Terms of Use the Platform will notify Augmont.<br />
                2) Once the payments are received by Augmont and the KYC information (if and where applicable) is found acceptable, Augmont shall issue an invoice to You confirming the Customer Order placed within a period of 3 (three) business days of placing such order, in a manner it may deem fit.<br />
                3) Notwithstanding anything to the contrary contained in these Terms and Conditions, Company and/or Augmont shall be entitled to accept or reject the User, for any reason whatsoever, at its sole and exclusive discretion. The money shall be refunded in case of order reject.<br />
                4) Once the Customer Order is placed, You are not entitled to cancel such a Customer Order, provided however that such Customer Order shall stand cancelled if the payment fails for any reason whatsoever. The Platform and/or Augmont reserves the right to cancel the Customer Order, at its sole discretion, if Your information, provided prior to placing the Customer Order, is not found acceptable and the Platform and/or Augmont are of the opinion that You are not eligible to purchase Gold from Augmont.<br />
                5) In case of rejection of any of Your Customer Order, where payments have been received by FiYDAA/ Augmont such payments shall be returned to You in accordance with these Terms of Use or the terms and conditions of Augmont as applicable.<br />
                6) The quantity of Gold purchased by You shall be stored with the Custodian in a vault on Your behalf. You hereby authorize Augmont to store such physical gold products purchased by You pursuant to the Customer Order, including, but not limited to, bullion, coins or jewellery (as the case may be) in the secured vault maintained by the Custodian on Your behalf (“Customer Gold”).<br />
                7) It is hereby clarified that Your purchase of the physical gold corresponding to Your Customer Order shall be deemed to be completed and title in relation thereto shall be deemed to have been passed to You upon such relevant portion of the Customer Gold being stored in the vault with the Custodian on Your behalf in accordance with the terms and conditions of Augmont, subject to applicable laws.<br />
                8) You will be provided with storage for your Customer Gold perpetually as per Augmont’s discretion, or for such period as more particularly stipulated by Augmont in this regard from time to time at its sole discretion and notified to Customers on the Platform (“Free Storage Period”).<br />
                9) Security Trustee: The Custodian has taken the necessary insurance policy/ies, in case of occurrence of an event not covered in such insurance policy/ies, the Customer Gold may be at risk. The insurance policy/ies obtained by the Custodian are in line with the global industry practices and cover losses due to fire, lightning, theft, cyclone, earthquake, flood, etc. but do not cover losses due to events such as war, revolution, derelict weapons of war, nuclear radiation, etc. In the event of any expenses or charges remaining payable to any Intermediaries or otherwise till actual delivery or fulfilment of any of Your Customer Orders for any reason, including where Augmont is unable to service such requests for any of its event of default, thereby adversely affecting or jeopardizing the fulfilment of Your Customer Orders, the details of the same shall be available at Augmont terms and conditions.<br /><br />

                <p class="text-2xl font-poppins mb-4">Pricing and Payment policy :</p>
                1) Except where noted otherwise, the price displayed on the App/Platform, represents the market linked price of Gold as indicated by Augmont.<br />
                2) Market linked prices means that these quotes are linked to the prices of gold in the commercial bullion market in India. However, it does not indicate that the gold prices displayed on the Platform will always be the same as that of the prevalent prices displayed in other commercial bullion markets. As a purchaser, it is your responsibility to compare the prices and take appropriate decisions after adequate diligence. Notwithstanding the foregoing, you understand that these prices may vary multiple times within a day, and accordingly<br />
                3) Your payment obligations for any Customer Order will depend on the prices displayed at the relevant time.<br />
                4) Payment policy: Payment will be accepted through the payment options made available on the App/ Platform, which may include redirection to a payment gateways and aggregators hosted by third-party websites or UPI applications.<br />
                5) At the time of purchase, fulfilment sale and/or transfer of Gold, the relevant taxes will be chargeable as applicable as per the Government regulations. However, please note that the detailed payment terms, delivery, warranty and cancellation and refund policy and other payment policy are subject to the terms and conditions of Augmont which can be accessed at {" "}  <a href="https://www.augmont.com/terms-conditions" style={{ color: '#0043e9' }}> https://www.augmont.com/terms-conditions</a><br /><br />

                <p class="text-2xl font-poppins mb-4">Delivery of Gold :</p>
                1) For the purposes of making delivery to You, You are required to provide a valid address and/or any other documents/information/ biometric identification that may be specified in this regard by Company and Augmont on the Platform from time to time. <br />
                2) You are required to take delivery of Your Customer Gold within such maximum period as shall be specified for this purpose by Augmont from time to time on the Platform In the event that no valid address has been provided by You during the maximum storage period, then Platform and/ Augmont shall for a period 1 (one) year commencing from the date of expiry of maximum storage period at its sole discretion attempt at least once to contact You using the contact information provided by You to obtain either (i) an address to which You would require the gold in question to be delivered or (ii) Your bank account details into which sale proceeds of the Gold shall be deposited. <br />
                3) In the event that Platform and/or Augmont has not been able to contact You during the additional period using the contact information provided by You, Augmont shall be entitled to purchase such Customer Gold with the purchase price being the applicable prevailing price displayed on the Platform for purchase of Gold from Customers as per details detailed in Augmont Terms and conditions. <br /> <br />

                <p class="text-2xl font-poppins mb-4">Return, Refund and Cancellation Policy :</p>
                1) On use of any coupon or discounts, as made available by us on the Platform or any other website or platform of any authorised third party, for purchase of Gold, the same shall be verified and adjusted, as may be necessary, within 7 (seven) days of use of such coupon or discount. <br />
                2) In case of any failed transactions you will be refunded in 6-8 business days.<br />
                3) Once the payment has been confirmed, the same shall be binding on You and cannot be cancelled. <br />
                4) You can opt out of auto investing on the Platform by undertaking the following actions: <br />
                5) There is no minimum lock-in period for the investment. <br />


                a) To pause :<br />
                (i) You'll find the pause button on the home screen under your savings. <br />
                (ii) You can choose the duration you wish to pause for. <br />
                b) To delete :<br />
                (i) Go into profile section, Select autopay, Select the mandate, Delete. <br />
                (ii) You can also delete the mandate via your UPI app <br /><br />


                <p class="text-2xl font-poppins mb-4">Offers and rewards :</p>
                From time-to-time FiYDAA may run marketing and promotional campaigns wherein it may provide offers which may include customer credits, promo codes, vouchers, rewards or any other form of incentive that FiYDAA may decide at its discretion. For the purpose of clarity, these Offer(s) shall be subject to certain additional terms and conditions, such as details of such Offer(s), validity etc. <br />
                You acknowledge that a particular Offer(s) cannot be clubbed with or used in conjunction with any other promotion, discount, vouchers or Offer(s).
                FiYDAA reserves the right to, modify specific terms applicable to each Offer(s) and/or these terms and conditions from time to time or at any time, reject, modify or discontinue, temporarily or permanently, any such Offer(s), with or without prior notice and the decision of FiYDAA shall be final and binding in this regard. In such cases, such revision will be updated on the FiYDAA application/platform accordingly.<br /> <br />

                <p class="text-2xl font-poppins mb-4">Intellectual Property Rights :</p>
                Intellectual Property Rights for the purpose of this Terms of Use shall always mean and include copyrights whether registered or not, patents including rights of filing patents, trademarks, trade names, trade dresses, house marks, collective marks, associate marks and the right to register them, designs both industrial and layout, geographical indicators, moral rights, broadcasting rights, displaying rights, distribution rights, selling rights, abridged rights, translating rights, reproducing rights, performing rights, communicating rights, adapting rights, circulating rights, protected rights, joint rights, reciprocating rights, infringement rights. All those Intellectual Property rights arising as a result of domain names, internet or any other right available under applicable law shall vest in the domain of FiYDAA or  entities as the owner of such domain name. The Parties hereto agree and confirm that no part of any Intellectual Property rights mentioned herein above is transferred in the name of User and any intellectual property rights arising as a result of these presents shall also be in the absolute ownership, possession and Our control or control of its licensors, as the case may be.<br />
                All material on this FiYDAA website and mobile application, including images, illustrations, audio clips, and video clips, are protected by copyrights, trademarks, and other intellectual property rights of Clearwater Capital Pvt Ltd. Material on Website is solely for Your personal, non-commercial use. You must not copy, reproduce, republish, upload, post, transmit or distribute such material in any way, including by email or other electronic means and whether directly or indirectly and You must not assist any other person to do so. Without the prior written consent of the owner, modification of the materials, use of the materials on any other platform or networked computer environment or use of the materials for any purpose other than personal, non-commercial use is a violation of the copyrights, trademarks and other proprietary rights, and is prohibited. <br />
                <br />


                <p class="text-2xl font-poppins mb-4">Termination :</p>
                You agree that FiYDAA at its sole discretion may terminate your contract without prior notice and restrict your access to the App/Platform if determined that You have violated the terms of use and You consent that in case FiYDAA suffers losses, not limited to monetary losses, due to Your actions, We can take injunctive relief or any other legal action as deemed necessary within the said circumstances and FiYDAA is not liable for any loss to You due to termination.<br /> <br />


                <p class="text-2xl font-poppins mb-4">Limitation of Liability :</p>
                Financial and non-financial transactions performed by You on the Platform is always processed by You or under Your exclusive authorization. <br />
                In no event will FiYDAA be liable for any indirect, consequential, incidental, special or punitive damages, including without limitation damages for loss of profits or revenues, business interruption, loss of business opportunities, loss of data or loss of other economic interests, whether in contract, negligence, tort or otherwise, arising from the use of or inability to use the Services, however caused and whether arising in contract, tort, negligence, warranty or otherwise. <br /> <br />


                <p class="text-2xl font-poppins mb-4">Indemnification :</p>
                You shall indemnify and hold harmless FiYDAA its owner, licensee, affiliates, subsidiaries, group companies (as applicable) and their respective officers, directors, agents, and employees, from any claim or demand, or actions including reasonable attorneys' fees, made by any third party or penalty imposed due to or arising out of Your breach of this Terms of Use, privacy Policy and other Policies, or Your violation of any law, rules or regulations or the rights (including infringement of intellectual property rights) of a third party. <br /> <br />

                <p class="text-2xl font-poppins mb-4">Force Majeure :</p>
                A Force Majeure Event shall mean any event that is beyond the reasonable control of FiYDAA and shall include but not limited to war, riots, fire, flood, acts of God, explosion, strikes, lockouts, slowdowns, prolonged shortage of energy supplies, Pandemic, computer hacking, unauthorized access to computer data and storage devices, computer crashes ,acts of state, governmental, legal or regulatory actions prohibiting or impeding FiYDAA from performing its respective obligations under the contract.
                <br /> <br />
                <p class="text-2xl font-poppins mb-4">Dispute, Governing Law & Jurisdiction :</p>
                This Agreement and the rights and obligations thereunder and the relations of the parties and all matters arising under or in connection with this Terms of Use, including the construction, validity, performance or termination thereunder, shall be governed by and construed in accordance with the laws of the Republic of India. Subject to and without prejudice to the amicable settlement, the courts in Panipat, Haryana shall have exclusive jurisdiction to try and adjudicate all matters arising in connection with your use of the Services or other matters covered herein.<br /> <br />


                <p class="text-2xl font-poppins mb-4">Disclaimers :</p>
                As part of this continual innovation and improvement, we sometimes may add or remove features and functionalities, increase, or decrease limits to our Services, start offering new services or stop offering old ones on our Platform. Such offering can also be due to discontinuation of any service or offering on the Platform by third party service providers or business partners. <br />

                We may record or monitor Our conventions with You for records and monitoring quality of our conversations. <br />

                Any content downloaded or otherwise obtained through the use of our Platform is done at your own discretion and risk, and We cannot confirm that such documents or contents are error or virus free and You understand and acknowledge that you are solely responsible for any damage to your devices, for any loss of data that may result from the download of such contents. <br />

                FiYDAA and third-party partners make no warranty, express or implied regarding the quality of Services including but not limited to: <br />

                1) the Services will meet your requirements <br />
                2) the Services will be uninterrupted, timely or error free; or<br />
                3) any products, information or material obtained by You in connection with the services will meet Your requirements.<br />
                Except as expressly provided herein and to the full extent permitted by law, the Services are provided "as is ", "as available " and "with all faults ". All such warranties, representations, conditions, undertakings and terms, whether express or implied, are hereby excluded. It is Your responsibility to evaluate the accuracy, completeness and usefulness of the Services and other information provided by FiYDAA or generally available. We do not authorize anyone to make any warranty on our behalf and You should not rely on any such statement.<br />

                If you have a dispute with other parties, you release FiYDAA (and our affiliates and officers, directors, agents, and employees thereof) from claims, demands and damages (actual and consequential) of every kind and nature, known and unknown, arising out of or in any way connected with such disputes.<br /> <br />


                <p class="text-2xl font-poppins mb-4">Contact Us :</p>
                <span style={{ color: "#0043e9", }}>

                    Clearwater Capital Pvt. Ltd. <br />
                    1st FLOOR, 945/3, Pachranga Bazar, Panipat, Haryana, 132103 <br />
                    Tel: +91 - 9053037500 <br />
                    Email: support@fiydaa.in <br /></span>



            </div>
            <Footer />

        </>
    )
}

export default TermsAndCondition